services:
  gateway.service:
    extends:
      file: ../.docker-compose.base.yml
      service: gateway_base
    networks:
      - app
    profiles:
      - mock
networks:
  app:
    name: ${APP_NETWORK}
    external: true
