services:
  gateway_base:
    environment:
      TRUST_DOWNSTREAM_PROXY: true
    image: nginxproxy/nginx-proxy:1.7
    profiles:
      - gateway_base
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERTS_DIR}:/etc/nginx/certs
