services:
  gateway_base:
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    image: traefik:v3
    profiles:
      - gateway_base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CERTS_DIR}:/certs:ro
