services:
  context_base:
    extends:
      service: stoobly_base
    volumes:
      - ${CONTEXT_DIR}/.stoobly:/home/stoobly/.stoobly
      - ${APP_DIR}/.stoobly/docker:/home/stoobly/.stoobly/docker
  stoobly_base:
    image: stoobly.${USER_ID}
  ui_base:
    extends:
      service: context_base 
    volumes:
      - ${CA_CERTS_DIR}:/home/stoobly/.mitmproxy