services:
  ui_base:
    extends:
      service: context_base 
    volumes:
      - ${CA_CERTS_DIR}:/home/stoobly/.mitmproxy   
  context_base:
    image: stoobly.${USER_ID}
    volumes:
      - ${CONTEXT_DIR}/.stoobly:/home/stoobly/.stoobly