ARG HOSTNAME=myhost.lab.ppops.net

FROM ubuntu:23.10 AS build

WORKDIR /tmp

RUN apt-get update && apt-get install -y curl
RUN curl -JLO "https://dl.filippo.io/mkcert/v1.4.4?for=linux/amd64" && \
  chmod +x mkcert-v1.4.4-linux-amd64

FROM ubuntu:23.10 AS cert

ARG HOSTNAME

COPY --from=build /tmp/mkcert-v1.4.4-linux-amd64 /bin/mkcert

RUN useradd -m mkcert

USER mkcert
WORKDIR /home/mkcert

RUN mkcert $HOSTNAME && mkcert -pkcs12 $HOSTNAME && cat $HOSTNAME.pem >> $HOSTNAME-joined.pem && cat $HOSTNAME-key.pem >> $HOSTNAME-joined.pem

FROM stoobly/agent:0.34

ARG USER_ID
ARG HOSTNAME

# Change user id of stoobly user to that of host's user id
USER root
RUN if [ -n "$USER_ID" ]; then usermod -u $USER_ID stoobly; fi

# Allow running stoobly on port 443
RUN apt-get update && apt-get install -y curl libcap2-bin
RUN setcap 'cap_net_bind_service=+ep' /usr/local/bin/python3.8
RUN chown -R stoobly:stoobly /home/stoobly

USER stoobly

COPY ./build/ .
COPY --from=cert /home/mkcert/$HOSTNAME-joined.pem .
