APP_NETWORK = '${APP_NETWORK}'
DOCKER_COMPOSE_BASE = '.docker-compose.base.yml'
DOCKER_COMPOSE_CUSTOM = 'docker-compose.yml'
DOCKERFILE_CONTEXT = '.Dockerfile.context'
DOCKERFILE_PROXY = '.Dockerfile.proxy'
DOCKERFILE_SERVICE = 'Dockerfile.source'
GATEWAY_NETWORK = 'gateway'
