FROM ubuntu:23.10 AS build

WORKDIR /tmp

RUN apt-get update && apt-get install -y curl
RUN curl -JLO "https://dl.filippo.io/mkcert/v1.4.4?for=linux/amd64" && \
  chmod +x mkcert-v1.4.4-linux-amd64

FROM ubuntu:23.10

ARG HOSTNAME
ARG USER_ID

COPY --from=build /tmp/mkcert-v1.4.4-linux-amd64  /bin/mkcert

# Changing mkcert user uid to USER_ID enables container to create files in mounted volume 
RUN if [ -z "$USER_ID" ]; then useradd -m mkcert; else useradd -m -u $USER_ID mkcert; fi

USER mkcert
WORKDIR /home/mkcert

ENTRYPOINT ["sh", "-c", "mkcert $HOSTNAME && mkcert -pkcs12 $HOSTNAME && cat $HOSTNAME.pem >> $HOSTNAME-joined.pem && cat $HOSTNAME-key.pem >> $HOSTNAME-joined.pem"]
