#! /bin/bash

# Add custom initialization and Stoobly configuration here.
#
# To learn more: https://docs.stoobly.com/core-concepts/agent/proxy-settings

app_path=$APP_DIR_MOUNT # Path to application source files

# For example, the below commands copies files inside a dist folder into the public folder. 
# The public folder is used when no recorded mocks are found.
#cp -r $app_path/dist/. public